// Run after next build against an isolated SQLite schema, never production.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { createServer } from 'node:http'
import { randomBytes } from 'node:crypto'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { realpathSync } from 'node:fs'
import sharp from 'sharp'
import { PrismaClient } from '@prisma/client'

test('local production API: registration, admin, image upload and account-isolated carts', async () => {
  const databaseUrl = process.env.TEST_DATABASE_URL
  assert.ok(databaseUrl?.startsWith('file:'), 'Requires explicit isolated TEST_DATABASE_URL')
  const relativeDatabasePath = path.relative(realpathSync.native(tmpdir()), realpathSync.native(fileURLToPath(databaseUrl)))
  assert.ok(relativeDatabasePath && !relativeDatabasePath.startsWith('..') && !path.isAbsolute(relativeDatabasePath), 'TEST_DATABASE_URL must be inside the OS temporary directory, never production')
  const suffix = randomBytes(6).toString('hex')
  const password = randomBytes(24).toString('hex')
  const uploads = await mkdtemp(path.join(tmpdir(), 'socialtool-uploads-'))
  const wireMock = createServer((req, res) => {
    res.setHeader('Content-Type', 'application/json')
    const id = req.url.split('/').pop()
    res.end(JSON.stringify({ id, status: 'succeeded', currency: 'MNT', amount: id === 'pi_wrong_amount' ? 1 : 300 }))
  })
  await new Promise(resolve => wireMock.listen(0, '127.0.0.1', resolve))
  const wireUrl = `http://127.0.0.1:${wireMock.address().port}/v1`
  const server = spawn(process.execPath, ['.next/standalone/server.js'], {
    env: { ...process.env, DATABASE_URL: databaseUrl, JWT_SECRET: randomBytes(32).toString('hex'), ADMIN_USERNAME: `admin-${suffix}`, ADMIN_PASSWORD: password, PORT: '3217', HOSTNAME: '127.0.0.1', UPLOAD_DIR: uploads, TELEGRAM_BOT_TOKEN: '', TELEGRAM_ADMIN_CHAT_ID: '', WIRE_MN_API_KEY: 'sk_test_local_mock_only', WIRE_MN_API_URL: wireUrl, WIRE_MN_ALLOWED_OPERATORS: '', WIRE_MN_WEBHOOK_SECRET: '', NEXT_PUBLIC_SITE_URL: 'http://127.0.0.1:3217' },
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  let logs = ''
  server.stdout.on('data', b => { logs += b })
  server.stderr.on('data', b => { logs += b })
  const db = new PrismaClient({ datasources: { db: { url: databaseUrl } } })
  const base = 'http://127.0.0.1:3217'
  const request = (route, options) => fetch(base + route, options)
  const json = (data, cookie) => ({ method: 'POST', headers: { 'Content-Type': 'application/json', ...(cookie ? { cookie } : {}) }, body: JSON.stringify(data) })
  const cookieOf = res => res.headers.get('set-cookie')?.split(';')[0]
  try {
    for (let i = 0; i < 60; i++) {
      try { if ((await request('/api/payment/wire/test')).ok) break } catch {}
      if (server.exitCode !== null) throw new Error('Server failed to start: ' + logs)
      await new Promise(r => setTimeout(r, 250))
    }
    const readiness = await request('/api/health/ready')
    assert.equal(readiness.status, 200)
    assert.equal((await readiness.json()).status, 'ok')
    const register = email => request('/api/auth/register', json({ name: 'Local Test', phone: '00000000', email, password }))
    const a = await register(`a-${suffix}@example.invalid`)
    assert.equal(a.status, 200)
    const accountA = (await a.json()).customer
    const cookieA = cookieOf(a)
    assert.ok(cookieA)
    assert.equal((await register(`a-${suffix}@example.invalid`)).status, 409)
    assert.equal((await register('not-an-email')).status, 400)
    const b = await register(`b-${suffix}@example.invalid`)
    assert.equal(b.status, 200)
    const cookieB = cookieOf(b)
    assert.equal((await request('/api/auth/me', { headers: { cookie: cookieA } })).status, 200)
    const admin = await request('/api/admin/login', json({ username: `admin-${suffix}`, password }))
    assert.equal(admin.status, 200)
    const token = (await admin.json()).token
    const adminHeaders = { authorization: `Bearer ${token}` }
    assert.equal((await request('/api/admin/session', { headers: adminHeaders })).status, 200)
    assert.equal((await request('/api/admin/session', { headers: { authorization: 'Bearer invalid' } })).status, 401)
    assert.equal((await request('/api/admin/products', { headers: adminHeaders })).status, 200)
    assert.equal((await request('/api/admin/integrations')).status, 401)
    const health = await request('/api/admin/integrations', { headers: adminHeaders })
    assert.equal(health.status, 200)
    assert.equal((await health.json()).checks.find(c => c.name === 'Telegram').ok, false)

    const category = await db.category.create({ data: { name: 'Local', slug: suffix, icon: 'Package' } })
    const product = await db.product.create({ data: { name: 'Local Test Product', duration: '1 жил;Хугацаагүй', slug: suffix, shortDesc: 'Test', description: '## Test\n\n- Item one\n- Item two', price: 100, category: category.name, categoryId: category.id } })
    // Smart commerce: catalog search, wishlist privacy, anonymous analytics,
    // grounded assistant fallback and authenticated product-health scans.
    assert.equal((await request('/api/customer/wishlist')).status, 401)
    assert.equal((await request('/api/customer/wishlist', json({ productId: product.id }))).status, 401)
    assert.equal((await request('/api/admin/analytics')).status, 401)
    assert.equal((await request('/api/admin/product-health')).status, 401)
    assert.equal((await request('/api/cron/product-health')).status, 503)
    await db.product.update({ where: { id: product.id }, data: { searchKeywords: 'uniquealias testing tag' } })
    const searchProducts = await (await request('/api/products?q=uniquealias')).json()
    assert.ok(searchProducts.some(item => item.id === product.id))
    const typoSuggestions = await (await request('/api/search/suggest?q=Locl')).json()
    assert.ok(typoSuggestions.suggestions.some(item => item.id === product.id))
    const saved = await request('/api/customer/wishlist', json({ productId: product.id }, cookieA))
    assert.equal(saved.status, 200)
    assert.equal((await request('/api/customer/wishlist', json({ productId: product.id }, cookieA))).status, 200)
    assert.equal((await (await request('/api/customer/wishlist', { headers: { cookie: cookieA } })).json()).items.length, 1)
    assert.equal((await (await request('/api/customer/wishlist', { headers: { cookie: cookieB } })).json()).items.length, 0)
    await db.product.update({ where: { id: product.id }, data: { price: 80 } })
    assert.equal((await (await request('/api/customer/wishlist', { headers: { cookie: cookieA } })).json()).items[0].priceDropped, true)
    await db.product.update({ where: { id: product.id }, data: { price: 100 } })
    const sid = '9ea201ce-4472-41ad-b883-' + randomBytes(6).toString('hex')
    const event = (type, more = {}) => request('/api/analytics/events', json({ type, sessionId: sid, ...more }))
    assert.equal((await event('product_view', { productId: product.id })).status, 200)
    assert.equal((await event('product_view', { productId: product.id })).status, 200)
    assert.equal((await event('cart_add', { productId: product.id })).status, 200)
    assert.equal((await event('search', { query: 'Local Test' })).status, 200)
    assert.equal((await event('checkout_start')).status, 200)
    assert.equal((await event('invalid_event')).status, 400)
    const analytics = await (await request('/api/admin/analytics?days=7', { headers: adminHeaders })).json()
    assert.ok(analytics.topViewed.some(item => item.productId === product.id && item.count === 1))
    assert.ok(analytics.topSearches.some(item => item.query === 'local test'))
    assert.ok(analytics.topWished.some(item => item.productId === product.id))
    const healthScan = await request('/api/admin/product-health', { headers: adminHeaders })
    assert.equal(healthScan.status, 200)
    const healthReport = await healthScan.json()
    assert.ok(healthReport.issues.some(issue => issue.productId === product.id && issue.code === 'short_description'))
    const assistant = await request('/api/assistant', json({ question: 'Local Test Product' }))
    assert.equal(assistant.status, 200)
    const advisor = await assistant.json()
    assert.ok(advisor.products.some(item => item.id === product.id))
    assert.ok(['ai', 'catalog'].includes(advisor.mode))
    assert.equal((await request('/api/customer/wishlist', { ...json({ productId: product.id }, cookieA), method: 'DELETE' })).status, 200)
    assert.equal((await (await request('/api/customer/wishlist', { headers: { cookie: cookieA } })).json()).items.length, 0)
    console.log('Verified smart search/tags, account-isolated wishlist and price drops, analytics, shopping assistant, product health, cron protection')

    const freeBody = { name:'Free program '+suffix, category:category.name, categoryId:category.id, price:0, downloadUrl:'https://example.org/free.zip' }
    const createFree = data => request('/api/admin/products', {...json(data),headers:{...adminHeaders,'Content-Type':'application/json'}})
    assert.equal((await request('/api/admin/products',json(freeBody))).status,401)
    for (const invalid of [{downloadUrl:'javascript:alert(1)'},{downloadUrl:null},{price:10},{duration:'1 жил'},{oldPrice:100},{requiresOrderLink:true}]) assert.equal((await createFree({...freeBody,...invalid})).status,400)
    const freeCreated=await createFree(freeBody)
    assert.equal(freeCreated.status,200)
    const free=await freeCreated.json()
    const freeListing=await (await request('/api/products?free=1')).json()
    assert.ok(freeListing.some(p=>p.id===free.id))
    assert.ok(freeListing.every(p=>p.price===0&&p.downloadUrl))
    assert.equal((await (await request('/api/products/'+free.id)).json()).downloadUrl,freeBody.downloadUrl)
    const freeUpdate=data=>request('/api/admin/products/'+free.id,{...json(data),method:'PUT',headers:{...adminHeaders,'Content-Type':'application/json'}})
    assert.equal((await freeUpdate({price:100})).status,400)
    assert.equal((await freeUpdate({downloadUrl:'http://example.org/unsafe'})).status,400)
    assert.equal((await freeUpdate({shortDesc:'Free download'})).status,200)
    const freeCurrent=await db.product.findUnique({where:{id:free.id}})
    assert.equal((await request('/api/admin/products/bulk-edit',{...json({items:[{id:free.id,updatedAt:freeCurrent.updatedAt.toISOString()}],patch:{price:{mode:'set',value:100,includeVariants:false}}}),method:'PUT',headers:{...adminHeaders,'Content-Type':'application/json'}})).status,400)
    assert.equal((await request('/api/orders',json({customerName:'Test',phone:'00000000',email:accountA.email,items:[{productId:free.id,name:free.name,price:100,quantity:1}]},cookieA))).status,400)
    console.log('Verified free program CRUD, HTTPS validation, paid/free invariant, filter and checkout/bulk-price protection')
    const png = await sharp({ create: { width: 16, height: 16, channels: 3, background: '#1677ff' } }).png().toBuffer()
    const form = new FormData()
    form.append('file', new Blob([png], { type: 'image/png' }), 'test.png')
    assert.equal((await request('/api/admin/products/upload', { method: 'POST', body: form })).status, 401)
    const uploaded = await request('/api/admin/products/upload', { method: 'POST', headers: adminHeaders, body: form })
    assert.equal(uploaded.status, 200)
    const uploadedUrl = (await uploaded.json()).url
    const image = await request(uploadedUrl)
    assert.equal(image.status, 200)
    assert.equal(image.headers.get('content-type'), 'image/webp')
    const storedImage = await db.uploadedImage.findUnique({ where: { filename: uploadedUrl.split('/').pop() } })
    assert.ok(storedImage.bytes.length > 0)
    assert.equal((await request(`/api/admin/products/${product.id}`, { ...json({ image: uploadedUrl }), method: 'PUT', headers: { ...adminHeaders, 'Content-Type': 'application/json' } })).status, 200)
    assert.equal((await (await request(`/api/products/${product.id}`)).json()).image, uploadedUrl)
    const sharePath = `/share/product/${product.id}`
    const shareHtml = await (await request(sharePath, { headers: { 'User-Agent': 'facebookexternalhit/1.1' } })).text()
    assert.match(shareHtml.split('</head>')[0], /property="og:image"/)
    assert.match(shareHtml, /property="og:image:width" content="1200"/)
    const thumbnail = await request(sharePath + '/image')
    assert.equal(thumbnail.status, 200)
    assert.match(thumbnail.headers.get('content-type'), /image\/png/)
    const thumbnailBytes = Buffer.from(await thumbnail.arrayBuffer())
    const thumbnailInfo = await sharp(thumbnailBytes).metadata()
    assert.equal(thumbnailInfo.width, 1200)
    assert.equal(thumbnailInfo.height, 630)
    const pixel = await sharp(thumbnailBytes).extract({ left:900, top:315, width:1, height:1 }).removeAlpha().raw().toBuffer()
    assert.ok(Math.abs(pixel[0]-22)<5 && Math.abs(pixel[1]-119)<5 && pixel[2]>250, 'Thumbnail must contain the actual uploaded blue image')
    await db.product.update({ where:{id:product.id}, data:{image:'https://example.invalid/product.jpg'} })
    const remoteShare = await (await request(sharePath, { headers:{'User-Agent':'facebookexternalhit/1.1'} })).text()
    assert.match(remoteShare, /property="og:image" content="https:\/\/example.invalid\/product.jpg"/)
    await db.product.update({ where:{id:product.id}, data:{image:uploadedUrl,available:false} })
    assert.equal((await request(sharePath+'/image')).status,404)
    await db.product.update({ where:{id:product.id}, data:{available:true} })
    console.log('Verified public Facebook metadata, real DB-uploaded 1200x630 thumbnail, external image metadata and unavailable product guard')
    assert.equal((await request('/api/admin/settings', { ...json({ heroImage: uploadedUrl }), method: 'PUT', headers: { ...adminHeaders, 'Content-Type': 'application/json' } })).status, 200)
    assert.equal((await (await request('/api/settings')).json()).heroImage, uploadedUrl)
    assert.equal((await request('/api/admin/settings', { ...json({ heroImage: 'javascript:alert(1)' }), method: 'PUT', headers: { ...adminHeaders, 'Content-Type': 'application/json' } })).status, 400)
    assert.equal((await request('/api/chat/messages', json({ sessionId:'x', sender:'admin', content:'spoof' }))).status, 400)
    // A fresh server process with a different empty upload directory reads the same DB image.
    const freshUploads = await mkdtemp(path.join(tmpdir(), 'socialtool-fresh-'))
    const secondServer = spawn(process.execPath, ['.next/standalone/server.js'], { env: { ...process.env, DATABASE_URL: databaseUrl, PORT: '3218', HOSTNAME: '127.0.0.1', UPLOAD_DIR: freshUploads }, stdio: 'ignore' })
    try {
      let secondImage
      for (let i=0;i<60;i++) {
        try { secondImage = await fetch('http://127.0.0.1:3218'+uploadedUrl); break } catch { await new Promise(r=>setTimeout(r,100)) }
      }
      assert.equal(secondImage?.status,200)
      assert.equal(secondImage.headers.get('content-type'),'image/webp')
    } finally { secondServer.kill('SIGTERM'); await rm(freshUploads, { recursive:true, force:true }) }
    console.log('Verified DB image survives fresh process/empty upload directory; product and hero persistence; invalid hero and admin chat spoof rejected')
    const invalid = new FormData()
    invalid.append('file', new Blob(['not an image'], { type: 'image/png' }), 'bad.png')
    assert.equal((await request('/api/admin/products/upload', { method: 'POST', headers: adminHeaders, body: invalid })).status, 400)

    assert.equal((await request('/api/customer/cart')).status, 401)
    const cartA = await (await request('/api/customer/cart', { headers: { cookie: cookieA } })).json()
    assert.equal(cartA.version, 0)
    const payload = { ownerId: accountA.id, version: 0, items: [{ id: product.id, quantity: 2 }] }
    const save = await request('/api/customer/cart', { ...json(payload, cookieA), method: 'PUT' })
    assert.equal(save.status, 200)
    assert.equal((await request('/api/customer/cart', { ...json(payload, cookieA), method: 'PUT' })).status, 409)
    assert.equal((await request('/api/customer/cart', { ...json(payload, cookieB), method: 'PUT' })).status, 403)
    assert.deepEqual((await (await request('/api/customer/cart', { headers: { cookie: cookieB } })).json()).items, [])
    const loginAgain = await request('/api/auth/login', json({ email: accountA.email, password }))
    assert.equal(loginAgain.status, 200)
    const secondDeviceCart = await (await request('/api/customer/cart', { headers: { cookie: cookieOf(loginAgain) } })).json()
    assert.equal(secondDeviceCart.items[0].quantity, 2)
    assert.equal(secondDeviceCart.items[0].price, 100)
    const variants = [{ id: product.id, duration: '1 жил', quantity: 1 }, { id: product.id, duration: 'Хугацаагүй', quantity: 2 }]
    assert.equal((await request('/api/customer/cart', { ...json({ ownerId: accountA.id, version: 1, items: variants }, cookieA), method: 'PUT' })).status, 200)
    const synced = await (await request('/api/customer/cart', { headers: { cookie: cookieOf(loginAgain) } })).json()
    assert.deepEqual(synced.items.map(i => i.duration), ['1 жил', 'Хугацаагүй'])
    const orderPayload = { customerName: 'Local Test', phone: '00000000', email: accountA.email, items: variants.map(i => ({ productId: i.id, duration: i.duration, quantity: i.quantity, price: 100, name: 'untrusted name' })) }
    const ordered = await request('/api/orders', json(orderPayload, cookieA))
    assert.equal(ordered.status, 200)
    const order = await db.order.findUnique({ where: { id: (await ordered.json()).orderId }, include: { items: true } })
    assert.equal(order.totalAmount, 300)
    assert.deepEqual(order.items.map(i => i.productName).sort(), ['Local Test Product — 1 жил', 'Local Test Product — Хугацаагүй'].sort())
    // A product's admin setting determines whether each ordered item needs its own link.
    const requireLinks = await request('/api/admin/products/' + product.id, {
      ...json({ requiresOrderLink: true }), method: 'PUT',
      headers: { ...adminHeaders, 'Content-Type': 'application/json' },
    })
    assert.equal(requireLinks.status, 200)
    assert.equal((await (await request('/api/products/' + product.id)).json()).requiresOrderLink, true)
    const requirements = await (await request('/api/products/order-link-requirements?ids='+product.id)).json()
    assert.equal(requirements.requirements[product.id], true)
    assert.equal((await (await request('/api/customer/cart', {headers:{cookie:cookieA}})).json()).items.every(i => i.requiresOrderLink), true)
    assert.equal((await request('/api/orders', json(orderPayload, cookieA))).status, 400)
    const socialLink = 'https://www.facebook.com/example/posts/123'
    const linkItems = orderPayload.items.map(i => ({...i, orderLink:socialLink}))
    const withLinks = await request('/api/orders', json({...orderPayload,items:linkItems}, cookieA))
    assert.equal(withLinks.status, 200)
    const linkedOrder = await db.order.findUnique({where:{id:(await withLinks.json()).orderId},include:{items:true}})
    assert.ok(linkedOrder.items.every(i=>i.orderLink===socialLink))
    const unsafeLinkItems = linkItems.map(i=>({...i,orderLink:'javascript:alert(1)'}))
    assert.equal((await request('/api/orders', json({...orderPayload,items:unsafeLinkItems}, cookieA))).status,400)
    assert.equal((await request('/api/admin/products/' + product.id, {
      ...json({requiresOrderLink:false}),method:'PUT',headers:{...adminHeaders,'Content-Type':'application/json'},
    })).status,200)
    assert.equal((await (await request('/api/products/' + product.id)).json()).requiresOrderLink,false)
    console.log('Verified required and optional per-product order links and URL safety')
    orderPayload.items[0].duration = 'invalid'
    assert.equal((await request('/api/orders', json(orderPayload, cookieA))).status, 400)
    console.log('Verified: two license variants sync between sessions; order retains authoritative name, term and total; invalid term rejected')
    assert.ok(order.chatSessionId)
    assert.equal(await db.chatMessage.count({where:{sessionId:order.chatSessionId,sender:'system'}}),0)
    const payment = await db.payment.create({ data: { orderId: order.id, amount: 300, wirePaymentIntentId: 'pi_wrong_amount' } })
    assert.equal((await request('/api/payment/wire/status?orderId='+order.id)).status,502)
    assert.equal((await db.payment.findUnique({ where:{id:payment.id} })).status,'PENDING')
    await db.payment.update({ where:{id:payment.id}, data:{wirePaymentIntentId:'pi_correct'} })
    const confirmed = await request('/api/payment/wire/status?orderId='+order.id)
    assert.equal(confirmed.status,200)
    assert.equal((await confirmed.json()).status,'PAID')
    assert.equal((await request('/api/customer/orders')).status,401)
    const paidHistory=await request('/api/customer/orders',{headers:{cookie:cookieA}})
    assert.match(paidHistory.headers.get('cache-control'),/no-store/)
    assert.equal((await paidHistory.json()).find(o=>o.id===order.id).status,'PAID')
    assert.deepEqual(await (await request('/api/customer/orders',{headers:{cookie:cookieB}})).json(),[])
    await db.order.update({ where:{id:order.id}, data:{status:'DELIVERED'} })
    assert.equal((await (await request('/api/customer/orders',{headers:{cookie:cookieA}})).json()).find(o=>o.id===order.id).status,'DELIVERED')
    await request('/api/payment/wire/status?orderId='+order.id)
    assert.equal((await db.order.findUnique({where:{id:order.id}})).status,'DELIVERED')
    const systemMessages = await db.chatMessage.findMany({where:{sessionId:order.chatSessionId,sender:'system'}})
    assert.equal(systemMessages.length,1)
    assert.ok(systemMessages[0].content.includes(order.orderNumber))
    const notices = await (await request('/api/customer/notifications', {headers:{cookie:cookieA}})).json()
    assert.equal(notices.notifications.length, 1)
    const notice = notices.notifications[0]
    assert.equal(notice.orderNumber, order.orderNumber)
    assert.equal(notice.readAt, null)
    assert.equal((await request('/api/customer/notifications')).status,401)
    assert.equal((await (await request('/api/customer/notifications',{headers:{cookie:cookieB}})).json()).notifications.length,0)
    await request('/api/customer/notifications',{...json({ids:[notice.id]},cookieB),method:'PATCH'})
    assert.equal((await db.chatMessage.findUnique({where:{id:notice.id}})).customerReadAt,null)
    assert.equal((await request('/api/customer/notifications',{...json({ids:[notice.id]},cookieA),method:'PATCH'})).status,200)
    const restoredNotices = await (await request('/api/customer/notifications',{headers:{cookie:cookieOf(loginAgain)}})).json()
    assert.ok(restoredNotices.notifications[0].readAt)
    console.log('Verified notifications persist across sessions, mark read, reject unauthenticated access and isolate customers')
    console.log('Verified: wrong payment amount cannot fulfill; valid amount confirms; delivered order does not regress')
    const pricedDuration = JSON.stringify([{ term: '1 жил', price: 120 }, { term: 'Хугацаагүй', price: 250 }])
    assert.equal((await request('/api/admin/products/' + product.id, { ...json({ duration: pricedDuration }), method: 'PUT', headers: { ...adminHeaders, 'Content-Type': 'application/json' } })).status, 200)
    const pricedCart = await (await request('/api/customer/cart', { headers: { cookie: cookieA } })).json()
    assert.deepEqual(pricedCart.items.map(i => i.price), [120, 250])
    const pricedPayload = { ...orderPayload, items: variants.map((i, n) => ({ productId: i.id, duration: i.duration, quantity: i.quantity, price: n ? 250 : 120, name: 'ignored' })) }
    const pricedOrder = await request('/api/orders', json(pricedPayload, cookieA))
    assert.equal(pricedOrder.status, 200)
    assert.equal((await pricedOrder.json()).amount, 620)
    pricedPayload.items[0].price = 1
    assert.equal((await request('/api/orders', json(pricedPayload, cookieA))).status, 400)
    assert.equal((await request('/api/admin/products/' + product.id, { ...json({ duration: JSON.stringify([{ term: '1 жил', price: -1 }]) }), method: 'PUT', headers: { ...adminHeaders, 'Content-Type': 'application/json' } })).status, 400)
    const slides = JSON.stringify([uploadedUrl, uploadedUrl])
    assert.equal((await request('/api/admin/settings', { ...json({ heroImages: slides }), method: 'PUT', headers: { ...adminHeaders, 'Content-Type': 'application/json' } })).status, 200)
    assert.equal((await (await request('/api/settings')).json()).heroImages, slides)
    assert.equal((await request('/api/admin/settings', { ...json({ heroImages: '["javascript:alert(1)"]' }), method: 'PUT', headers: { ...adminHeaders, 'Content-Type': 'application/json' } })).status, 400)
    console.log('Verified: per-term prices persist, carts refresh, authoritative order total and tamper rejection; slideshow settings persist and reject unsafe paths')
    await db.product.update({ where:{id:product.id}, data:{duration:null} })
    const pieceCart = await (await request('/api/customer/cart', {headers:{cookie:cookieA}})).json()
    assert.equal(pieceCart.items.length,1)
    assert.equal(pieceCart.items[0].duration,'')
    assert.equal(pieceCart.items[0].quantity,3)
    const pieceOrder = { customerName:'Local Test', phone:'00000000',email:accountA.email,items:[{productId:product.id,name:'ignored',price:100,quantity:12,duration:''}] }
    const placed = await request('/api/orders',json(pieceOrder,cookieA))
    assert.equal(placed.status,200)
    assert.equal((await placed.json()).amount,1200)
    pieceOrder.items[0].duration='1 жил'
    assert.equal((await request('/api/orders',json(pieceOrder,cookieA))).status,400)
    console.log('Verified admin disabling license terms merges cart lines; piece quantity total; disabled term rejected')
    const peer = await db.product.create({data:{name:'Bulk peer',slug:suffix+'-bulk',shortDesc:'',description:'',price:100,category:category.name,categoryId:category.id}})
    const beforeBulk = await db.product.findUnique({where:{id:product.id}})
    const bulk = (items, authorized=true) => request('/api/admin/products/bulk-images',{...json({items}),method:'PUT',headers:{'Content-Type':'application/json',...(authorized?adminHeaders:{})}})
    const rows = [{id:product.id,previousImage:beforeBulk.image,image:'/products/default/ai.svg'},{id:peer.id,previousImage:null,image:'/products/default/windows.svg'}]
    assert.equal((await bulk(rows,false)).status,401)
    assert.equal((await bulk(rows)).status,200)
    assert.equal((await db.product.findUnique({where:{id:product.id}})).image,rows[0].image)
    assert.equal((await db.product.findUnique({where:{id:peer.id}})).image,rows[1].image)
    assert.equal((await bulk([{id:product.id,previousImage:rows[0].image,image:'/products/default/facebook.svg'},{id:peer.id,previousImage:null,image:'/products/default/facebook.svg'}])).status,409)
    assert.equal((await db.product.findUnique({where:{id:product.id}})).image,rows[0].image)
    assert.equal((await bulk([{id:product.id,previousImage:rows[0].image,image:'javascript:alert(1)'}])).status,400)
    assert.equal((await bulk([{id:product.id,previousImage:rows[0].image,image:uploadedUrl}])).status,200)
    const sitemap = await request('/sitemap.xml')
    assert.equal(sitemap.status,200)
    const sitemapText = await sitemap.text()
    assert.ok(sitemapText.includes('<urlset'))
    assert.ok(!sitemapText.includes('/admin'))
    assert.equal((await request('/robots.txt')).status,200)
    assert.equal((await request('/icon.svg')).status,200)
    console.log('Verified bulk images: auth, two-product save, atomic conflict rollback, invalid-image rejection; sitemap, robots and favicon routes')
    const logout = await request('/api/admin/session', { method: 'DELETE', headers: adminHeaders })
    assert.match(logout.headers.get('set-cookie'), /Max-Age=0/i)
    console.log('Verified: registration, duplicate rejection, login, admin session, upload/read, invalid image, two-device cart and account isolation')
  } finally {
    server.kill('SIGTERM')
    wireMock.close()
    await db.$disconnect()
    await rm(uploads, { recursive: true, force: true })
  }
})
