import { createRequire } from 'node:module'
import assert from 'node:assert/strict'
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:3100'
assert.ok(['localhost', '127.0.0.1'].includes(new URL(base).hostname))
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_EXECUTABLE })
try {
  const page = await browser.newPage({ reducedMotion: 'reduce' })
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await page.route('**/api/assistant', route => route.fulfill({ json: { answer: 'Туршилтын хариулт', mode: 'catalog', products: [] } }))
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 850 })
    await page.goto(base, { waitUntil: 'domcontentloaded' })
    const hub = page.locator('.support-hub')
    await hub.getByRole('button', { name: 'Тусламж', exact: true }).click()
    await hub.getByRole('button', { name: 'AI-аас асуух', exact: true }).click()
    await hub.getByRole('textbox', { name: 'Зөвлөхөөс асуух' }).fill('Хадгалах асуулт')
    await hub.locator('nav').getByRole('button', { name: 'Админтай холбогдох', exact: true }).click()
    await hub.getByRole('textbox', { name: 'Нэр', exact: true }).fill('Туршилт')
    await hub.getByRole('button', { name: 'AI-аас асуух', exact: true }).click()
    assert.equal(await hub.getByRole('textbox', { name: 'Зөвлөхөөс асуух' }).inputValue(), 'Хадгалах асуулт')
    await hub.getByRole('button', { name: 'Илгээх', exact: true }).click()
    await hub.getByText('Туршилтын хариулт', { exact: true }).waitFor()
    await page.evaluate(() => window.dispatchEvent(new Event('st-open-chat')))
    assert.equal(await hub.getByRole('textbox', { name: 'Нэр', exact: true }).inputValue(), 'Туршилт')
    const bounds = await page.locator('#support-options').boundingBox()
    assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= width && bounds.y >= 0)
    await page.keyboard.press('Escape')
    assert.equal(await page.locator('#support-options').isVisible(), false)
    assert.equal(await hub.getByRole('button', { name: 'Тусламж', exact: true }).evaluate(el => el === document.activeElement), true)
    console.log(`Support ${width}: channel switching, draft preservation, AI reply, FAQ event, keyboard and bounds passed`)
  }
  const products = await (await page.request.get(base + '/api/products')).json()
  const product = products.find(p => p.available && p.price > 0)
  assert.ok(product)
  await page.goto(base + '/?product=' + product.id, { waitUntil: 'domcontentloaded' })
  const dialog = page.getByRole('dialog')
  await dialog.locator('.purchase-quantity').waitFor()
  assert.equal(await page.locator('.support-launcher').isVisible(), false)
  assert.equal(await dialog.getByRole('button', { name: 'Тоо ширхэг багасгах' }).isDisabled(), true)
  await dialog.getByRole('button', { name: 'Тоо ширхэг нэмэх' }).click()
  assert.equal(await dialog.locator('.purchase-quantity output').textContent(), '2')
  await dialog.getByRole('button', { name: /Сагсанд нэмэх ·/ }).click()
  await page.getByText('Таны сагс', { exact: true }).waitFor()
  assert.equal(await page.locator('.support-launcher').isVisible(), false)
  assert.equal(await dialog.locator('.purchase-quantity output').textContent(), '2')
  await dialog.getByRole('button', { name: 'Тоо ширхэг багасгах' }).click()
  assert.equal(await dialog.locator('.purchase-quantity output').textContent(), '1')
  assert.equal(await dialog.getByRole('button', { name: 'Тоо ширхэг багасгах' }).isDisabled(), true)
  await page.keyboard.press('Escape')
  await page.locator('.support-launcher').waitFor()
  await page.evaluate(() => document.documentElement.classList.add('dark'))
  await page.locator('.support-launcher').click()
  assert.equal(await page.locator('#support-options').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(17, 30, 48)')
  assert.deepEqual(errors, [])
  console.log('Purchase controls: shared quantity, cart transfer, overlay suppression, dark surface and browser errors passed')
} finally { await browser.close() }
